# Generated by Django 4.2.2 on 2023-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_when_started', models.TimeField()),
                ('number_of_turns', models.IntegerField()),
                ('ended_early', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('user_bio', models.CharField(max_length=512)),
                ('experience', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
    ]
