# Generated by Django 4.2.2 on 2023-06-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='description',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
    ]
