# Generated by Django 4.2.2 on 2023-06-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_trophy_owner_remove_trophy_time_when_recieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedtrophy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.trophy'),
        ),
    ]
