# Generated by Django 4.2.2 on 2023-06-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_grantedtrophy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('time', models.TimeField()),
                ('on_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_profile.user')),
            ],
        ),
    ]
