# Generated by Django 4.2.2 on 2023-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_supportticket_alter_commentary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='assignee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
