# Generated by Django 4.2.1 on 2023-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=25)),
                ('msg', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='note',
        ),
    ]
