# Generated by Django 4.2.1 on 2023-05-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_note_remove_weekday_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.weekday'),
        ),
    ]
