name: Running lint and tests.py
on:
  - push
  - pull_request

jobs:
  check_style_consistency:
    name: Check style consistency
    runs-on: ubuntu
    steps:
      - name: Checkout repository code
        uses: actions/checkout@ver3
      - name: Install requierements
        run: pip install flake8 django
      - name: Execute flake8 linter
        run: flake8 monopoly/.flake8
